# Generated by Django 4.1.3 on 2022-12-09 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
